### ISSUE TITLE
source-only apps?

### ISSUE THREAD

**Issue by mark-pictor-csec** [geeksonsecurity/vuln-web-apps#5]
Hi,

Any plans to add apps that are only available as source, not running on a publicly-accessible website?

If so, maybe it'd make sense to have two lists - one for apps which have source available and one for apps which don't.

**Comment by ayboraa** [comment]
Any updates on this?

**Comment by wizche** [comment]
Hi @mark-pictor-csec and @ayboraa, we dont actively plan this, but we are very welcome to PRs :smiley:
